[package]
name = "TailTerm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.18.4"
gtk = "0.18.1"
qt_core = "0.5.0"
qt_widgets = "0.5.0"
tokio = "1.35.0"
vte = "0.13.0"
